name: files-service-test

services:
  files-service:
    container_name: files-service
    env_file: .env
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: dev
    userns_mode: "keep-id"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/keys/gdrive.keys.json
    working_dir: /usr/src/app
    ports:
      - "9229:9229"
      - "${SERVICE_PORT:-3000}:${SERVICE_PORT:-3000}"
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./yarn.lock:/usr/src/app/yarn.lock
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./tsconfig.build.json:/usr/src/app/tsconfig.build.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
      - ./.env:/usr/src/app/.env
      - ./keys/gdrive.keys.json:/keys/gdrive.keys.json:ro
    depends_on:
      - postgres
      - pgadmin
      - redis
    command: ["sleep","infinity"]  

  postgres:
    container_name: files-service-postgres
    env_file: .env
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /data/postgres
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/data/postgres

  pgadmin:
    container_name: files-service-pgadmin
    env_file: .env
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  redis:
    container_name: files-service-redis
    env_file: .env
    image: redis:8.0.2-alpine
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER: ${REDIS_USER}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
  redis_data: